# fly.toml app configuration file generated for conciergetgbot-summer-sun-491 on 2025-06-20T22:28:24-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'conciergetgbot-summer-sun-491'
primary_region = 'yyz'

[http_service]
  internal_port = 8080
  force_https = true
  min_machines_running = 0
  max_machines_running = 1
  processes = ['app']

[mounts]
  source = "concierge_bot"
  destination = "/data"

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
